### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by jfuruness** [remiflavien1/mitrecve#6]
Minimal reproducible error on the latest version:

```
from mitrecve import crawler

crawler.get_cve_detail("libstdc++6")

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    crawler.get_cve_detail("libstdc++6")
  File "/home/anon/env/lib/python3.8/site-packages/mitrecve/crawler.py", line 172, in get_cve_detail
    ref_links = soup.select("#GeneratedTable > table > tr > td > ul")[0].find_all("a") 
IndexError: list index out of range
```

**Comment by shadawck** [comment]
There is a new working version (see #7)

New way to get detail. First crawl the cve then build details.
>>> results_cve = crawler.get_main_page("libstdc++6")
>>> crawler.get_cve_detail(results_cve)
